travis:
  secure:
    BINSTAR_TOKEN: T9SyKOLP4JOQE4QeKiud+/rGTo2Wvrt0xXEgoTqPID2x9XvoLPD1cqRhpbnaqIzoQkjHfuiFBtVEpfWey0ZMQ4YqnuadWxdTTTFhJq35v0XapEvxnzaHO8fMzfbgvqGLyLAoSnC97Y2eWYxn5KmiznQjYy6rsUzMmo2Yhdq/QvESRpsKb/Q2p/H65uT9Dg+74OL82LluI6V8ZFhYk1QhANLvb2bHYUgXWwENmzcmLAsgbLMHxw2nNSf1HHz2pBvp/62BprzdHZ+UEAnq3RnEQ4Bw3b231tvOei1WcTTltTlpN9m0kv8wMA00d+XbxxqmKD9kwlxHYUoY/Z2gPm/b2gq2fqs3hsxu+FhCHJRmyF3H5Rqwj445XHOiE+bGBRtZMsLHHFA2jrhmKbyZAA/I1PhXLktR5OWw7Io2q3hW1DJtIDWv3TixerVNZBXtdSW0fSedNslgH7dYlNJt+2WGjluZnwCixG0psPH5sxiE40O3daHnhDSpJDJyUVV5vUCfKRn07S1jsFo6y7PI/nnWfMf2OH/tl5YV8/CwE5lvo/D5y1Vk4p9ZClvN7VuC6TIsUM7WG8xLolSvT+mBcMtFzgQPwBi0WFu/uZRCDH/SVeeSxfJWcXbONyAeXsKuvCAwukoW+xya0i3yZmC/6I5abd8QL9Xygo/+PtMMprMMJQc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
